### ISSUE TITLE
[DD] Always set dd-handle class on handles or main element

### ISSUE THREAD

**Issue by drjayvee** [yui/yui3#1055]
Currently, if you want to style a drag handle, the CSS has to "know" which element is the handle (could be the configuration's `node` or any child nodes).

The [Drag - Node plugin example](http://yuilibrary.com/yui/docs/dd/drag-plugin.html) has the following code:

``` css
.example .demo .yui-hd {
  /* bla */
  cursor: move;
}
```

and

``` js
node.dd.addHandle('.yui-hd');
```

Problem: the CSS author has to know where the js author places the drag handle. If the js changes, then the CSS has to be updated as well.

I would propose adding a class (e.g. `dd-handle`) on every drag handle, _or_ the main node if none is set.

`dd` could even get a `dd-core.css` that contains only

``` css
.dd-handle {
  cursor: move;
}
```

I can take a shot at implementing this, if there's consensus this would be a good thing.
